quarkus:
  application:
    name: "ledgerforge"
  datasource:
    db-kind: mssql
    username: sa
    password: 524udb764L9aCxEJ
    jdbc:
      url: jdbc:sqlserver://192.168.65.254:1433;databaseName=OFTL_LEDGERFORGE;encrypt=false;trustServerCertificate=false;loginTimeout=60
      acquisition-timeout: 60s
  hibernate-orm:
    database: 
      generation: none
  http:
    port: 8080
    host: 0.0.0.0
    root-path: '/v1/ledgerforge'
  log:
    level: INFO
    console:      
      color: true      
      level: INFO
  jackson:
    serialization-inclusion: NON_EMPTY
      
appconfig:  
  statusMappingJSON: '{"NO_AUTH_HEADER":{"code":"9100","HTTP_CODE":"403","EN":"Authentication Failure","AR":"فشل المصادقة"},"NO_MSSG_ID":{"code":"9101","HTTP_CODE":"400","EN":"Required Input Missing: Message ID","AR":"فشلإدخال المطلوب مفقود: معرف الرسالة"},"SUCCESS":{"code":"0000","HTTP_CODE":"200","EN":"Success","AR":"نجاح"},"BERR_NO_RECORD_FOUND":{"code":"8001","HTTP_CODE":"404","EN":"No Record Found","AR":"لم يتم العثور على سجل"}}'  
  