quarkus:
  application:
    name: "ledgerforge"

  http:
    port: 8080
    root-path: '/v1/ledgerforge'
  log:
    level: INFO
    console:      
      color: true      
      level: INFO
      
appconfig:  
  statusMappingJSON: '{"NO_AUTH_HEADER":{"code":"9100","EN":"Authentication Failure","AR":"فشل المصادقة"}}'
  