quarkus:
  application:
    name: "ledgerforge"

  http:
    port: 8080
    host: 0.0.0.0
    root-path: '/v1/ledgerforge'
  log:
    level: INFO
    console:      
      color: true      
      level: INFO
      
appconfig:  
  statusMappingJSON: '{"NO_AUTH_HEADER":{"code":"9100","EN":"Authentication Failure","AR":"فشل المصادقة"},"NO_MSSG_ID":{"code":"9101","EN":"Required Input Missing: Message ID","AR":"فشلإدخال المطلوب مفقود: معرف الرسالة"},"SUCCESS":{"code":"0000","EN":"Success","AR":"نجاح"}}'  
  test: "test"
  